### ISSUE TITLE
Как через новый android sdk сделать refreshToken?

### ISSUE THREAD

**Issue by flexer1992** [apiok/android_example#4]

**Comment by thefilin** [comment]
Через SDK проходит [клиентский OAuth](https://apiok.ru/wiki/pages/viewpage.action?pageId=81822117), который не требует секретного ключа.
refreshToken - это относится к [серверному OAuth](https://apiok.ru/wiki/pages/viewpage.action?pageId=81822109), где нужен секретный ключ, зашитый в приложение.
